import type { Metadata } from "next";
import "./globals.css";
import clsx from 'clsx';
import { lato } from "../lib/fonts";
import Header from "@/components/header";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Next JS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(lato.className)}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
